server:
    port: 8080

keycloak:
  auth-server-url: # set ENV KEYCLOAK_AUTH_URL
  realm: # set ENV KEYCLOAK_REALM_NAME
  resource: # set ENV KEYCLOAK_CLI
  credentials:
    secret: # Mandatory if not public-client. set ENV KEYCLOAK_SECRET
  principal-attribute: preferred_username
  public-client: false # default value. set ENV KEYCLOAK_PUBLIC_CLI to change

spring:
  datasource:
    url: # set ENV DB_URL
    username: # set ENV DB_USERNAME
    password: # set ENV DB_PASSWORD
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      generate_statistics: false